### PR TITLE
Rename AccelerometerSensor interface to Accelerometer

### PR DESCRIPTION
**Pull request by alexshalamov**
Based on TPAC consensus related to concrete sensor naming, rename AccelerometerSensor interface to Accelerometer.

### CODE REVIEW

**Comment by anssiko** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by anssiko** [comment]
Thanks! Go ahead and merge.

(@dontcallmedom Ash-Nazg complained about ipr check. I marked this PR as non-substantantive in the Repo Manager as a fix: https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/accelerometer/8)

**Comment by dontcallmedom** [comment]
I've add @alexshalamov to the IPR checker so that his future contributions will get the proper blessing.

**Comment by anssiko** [comment]
@alexshalamov r+ so feel free to merge this PR.

@dontcallmedom Thanks, the same for @pozdnyakov and w3c/gyroscope please :-)

**Comment by dontcallmedom** [comment]
@pozdnyakov added too :) (and his PR revalidated under the Intel affiliation)

**Pull request merged**
